Fix configuring annocheck without gcc-plugin.  Fix debuginfod test

diff --git a/tests/debuginfod-test b/tests/debuginfod-test
--- a/tests/debuginfod-test
+++ b/tests/debuginfod-test
@@ -33,14 +33,16 @@ if [ -z $(command -v $CURL) ]; then
 fi
 
 if [ -z $(command -v $SS) ]; then
-  echo "$FAIL Could not find ss"
+  echo "$FAIL Could not find $SS"
   exit 1
 fi
 
 start_test
 
-$GCC -fplugin=$PLUGIN $PLUGIN_OPTS -g -c $srcdir/hello.c $srcdir/hello2.c $srcdir/hello3.c $srcdir/hello_lib.c
-$GCC hello.o hello2.o hello3.o hello_lib.o -o debuginfod-test.exe
+OPTS="$(rpm --eval '%build_cflags %build_ldflags')"
+
+$GCC $OPTS -c $srcdir/hello.c $srcdir/hello2.c $srcdir/hello3.c $srcdir/hello_lib.c
+$GCC hello.o hello2.o hello3.o hello_lib.o $OPTS -o debuginfod-test.exe
 
 $OBJCOPY --only-keep-debug debuginfod-test.exe debuginfod-test.dbg
 $OBJCOPY --strip-debug debuginfod-test.exe
@@ -57,7 +59,7 @@ export DEBUGINFOD_CACHE_PATH=${PWD}/.debuginfod_cache
 # Find an unused port number
 while true; do
     PORT=`expr '(' $RANDOM % 1000 ')' + 9000`
-    ss -atn | fgrep ":$PORT" || break
+    $SS -atn | fgrep ":$PORT" || break
 done
 
 DB=${PWD}/.debuginfod.db
