Various minor bugfixes found whilst attempting to build an rpm

diff --git a/tests/hardening-test b/tests/hardening-test
--- a/tests/hardening-test
+++ b/tests/hardening-test
@@ -20,50 +20,54 @@ OBJCOPY=objcopy
 
 PLUGIN=../plugin/.libs/annobin.so
 
-OPTS="-c -O2 -D_FORTIFY_SOURCE=2 -fpie -Wall -fstack-protector-strong -D_GLIBCXX_ASSERTIONS -fstack-clash-protection -fcf-protection"
+OPTS="-c -O2 -D_FORTIFY_SOURCE=2 -fpie -Wall -fstack-protector-strong -D_GLIBCXX_ASSERTIONS -fstack-clash-protection"
+EXTRA_OPTS="-fcf-protection -mstackrealign"
 
-$GCC -fplugin=$PLUGIN -g $OPTS  $srcdir/hello_hard.c 
+$GCC -fplugin=$PLUGIN -g $OPTS $EXTRA_OPTS  $srcdir/hello_hard.c 
 if [ $? != 0 ];
 then
     echo "Compiler might not support -fcf-protection, retrying without it"
-    OPTS="-c -O2 -D_FORTIFY_SOURCE=2 -fpie -Wall -fstack-protector-strong -D_GLIBCXX_ASSERTIONS -fstack-clash-protection"
-    $GCC -fplugin=$PLUGIN -g $OPTS  $srcdir/hello_hard.c 
+    EXTRA_OPTS="-mstackrealign"
+    $GCC -fplugin=$PLUGIN -g $OPTS  $EXTRA_OPTS $srcdir/hello_hard.c 
     if [ $? != 0 ];
     then
-	exit 0
+	echo "Compiler might not support -mstackrealign, retrying without it"
+	EXTRA_OPTS="-fcf-protection"
+	$GCC -fplugin=$PLUGIN -g $OPTS $EXTRA_OPTS $srcdir/hello_hard.c 
+	if [ $? != 0 ];
+	then
+	    echo "Compiler might not support either -fcf-protection or -mstackrealign, retrying without both"
+	    EXTRA_OPTS=""
+	    $GCC -fplugin=$PLUGIN -g $OPTS $EXTRA_OPTS $srcdir/hello_hard.c 
+	    if [ $? != 0 ];
+	    then
+		echo "Failed :-("
+		exit 1
+	    fi
+	fi
     fi
 fi
 
-$GCC -fplugin=$PLUGIN -O3 $OPTS $srcdir/hello2.c 
+$GCC -fplugin=$PLUGIN -O3 $OPTS $EXTRA_OPTS $srcdir/hello2.c 
 
-$GCC -fplugin=$PLUGIN -g3 $OPTS $srcdir/hello3.c
+$GCC -fplugin=$PLUGIN -g3 $OPTS $EXTRA_OPTS $srcdir/hello3.c
 
-$GCC -fplugin=$PLUGIN $OPTS -shared $srcdir/hello_lib.c -o libhello.so
+$GCC -fplugin=$PLUGIN $OPTS $EXTRA_OPTS -shared $srcdir/hello_lib.c -o libhello.so
 
-$GCC -fplugin=$PLUGIN -nostartfiles -e 0 \
+# Link without system files as these may not have been hardened.
+$GCC -fplugin=$PLUGIN \
+     -nostartfiles -nostdlib -Wl,-e,0 \
+     -Wl,--defsym=__stack_chk_fail=0 \
+     -Wl,--defsym=__stack_chk_fail_local=0 \
+     -Wl,--defsym=__stack_chk_guard=0 \
+     -Wl,--defsym=__printf_chk=0 \
      -L . -pie \
      -Wl,-z,now,-z,relro \
  hello_hard.o hello2.o hello3.o -lhello -o hardening-test.exe
 
 # $OBJCOPY --merge-notes hardening-test.exe hardening-test-merged.exe
 
-# The --skip=... options are here to skip the checks that require a version
-# 2.30 (or later) readelf, and which were generated by a plugin attached to
-# a version 8 (or later) gcc.  Since neither of these versions of the tools
-# are in common use (yet) the checks are disabled.
-# The other hardening properties can be deduced by the hardened script
-# without needing the notes produced by annobin, so that is why the test is
-# allowed to proceed.
-# FIXME: Remove the --skip= options once readelf and gcc have been updated.
-#
-# The --skip-pic and --skip-stack options are here because /usr/lib64/libc_nonshared.a(elf-init.oS)
-# is built with -fPIC and -fno-stack-protection.  /usr/lib64/Scrti.o is built
-# with -fpie which makes the pic test impossible.
+# The s390 and PPC targets always create some gaps.  Have not found out why...
 
-# $srcdir/../scripts/hardened  --readelf=$READELF \
-#   --skip=fort -k=operator --skip=clash --skip=cf -k=cet \
-#   --skip=pic --skip=stack --skip=realign \
-#   hardening-test.exe
-
-../annocheck/annocheck hardening-test.exe
+../annocheck/annocheck -v --ignore-gaps hardening-test.exe
 
