9.56: Annobin testing improvements + fixed format messages

diff --git a/tests/lto-test b/tests/lto-test
--- a/tests/lto-test
+++ b/tests/lto-test
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright (c) 2017-2020 Red Hat.
+# Copyright (c) 2017-2021 Red Hat.
 #
 # This is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published
@@ -35,4 +35,12 @@ $GCC -fplugin=$PLUGIN $PLUGIN_OPTS \
 
 # Run annocheck, but only enable the LTO test.
 
-$ANNOCHECK -v --ignore-gaps --skip-all --test-lto lto-test.exe | grep -e "PASS: Compiled with LTO enabled"
+$ANNOCHECK -v --ignore-gaps --skip-all --test-lto lto-test.exe --fixed-format-messages > lto-test.out
+
+grep -e "PASS: test: lto" lto-test.out
+if [ $? != 0 ];
+then
+    echo "lto-test: FAIL: did not detect LTO compilation"
+    cat lto-test.out
+    exit 1
+fi
diff --git a/tests/objcopy-test b/tests/objcopy-test
--- a/tests/objcopy-test
+++ b/tests/objcopy-test
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright (c) 2017-2020 Red Hat.
+# Copyright (c) 2017-2021 Red Hat.
 #
 # This is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published
@@ -39,4 +39,12 @@ $OBJCOPY --merge-notes objcopy-test.exe objcopy-merged.exe
 
 # Run annocheck, but only enable the LTO test.
 
-$ANNOCHECK -v --ignore-gaps --skip-all --test-optimization objcopy-merged.exe | grep -e "PASS: Compiled with sufficient optimization"
+$ANNOCHECK -v --ignore-gaps --skip-all --test-optimization objcopy-merged.exe > objcopy-test.out
+grep -e "PASS: optimization test" objcopy-test.out
+if [ $? != 0 ];
+then
+    echo "objcopy-test: FAIL: did not confirm sufficient optimization"
+    cat objcopy-test.out
+    exit 1
+fi
+
